# Databricks notebook source
# -----------------------------------------------------------------------------
# Bronze Layer: Threat Intelligence Feed Ingestion
# -----------------------------------------------------------------------------
# Fetches the 3 configured threat intel feeds via HTTP GET, parses each feed's
# format, and appends extracted IOC rows to bronze.threat_intel_raw.
#
# This is a batch job (not streaming) — feeds are static files that are
# regenerated by their publishers daily. HTTP fetches run on the driver node.
#
# What is stored vs. not stored:
#   STORED:   one row per IOC value, the feed name, the fetch timestamp, and
#             any per-row structured metadata the feed provides (e.g., Feodo
#             provides port and malware family per C2 IP)
#   NOT STORED: full HTTP response bodies. Only the specific fields needed
#             for normalization and correlation are extracted and persisted.
#
# Feed failure handling:
#   Each feed is fetched independently inside a try/except block. A timeout,
#   HTTP error, or parse failure for one feed logs a warning and continues —
#   the run does not abort. Feeds that fail are absent from the current bronze
#   batch; their silver indicators will retain last_seen_at until 2× TTL
#   causes a hard delete. If ALL feeds fail, the job aborts with a clear error.
#
# Bronze retention:
#   After writing new rows, rows older than 14 days are hard deleted.
#   Each daily run adds ~10–20K rows; 14-day retention keeps the table at
#   ~140–280K rows while preserving enough history to debug silver issues.
#
# Feed formats:
#   feodo_tracker    — CSV: dst_ip, dst_port, c2_status, first_seen_utc,
#                           last_seen_utc, malware  (# comment lines)
#   emerging_threats — Plain text: one IP per line  (# comment lines)
#   ipsum            — Tab-separated: IP <TAB> list-count score  (# comment lines)
#
# Source:  HTTP GET (no authentication required)
# Target:  security_poc.bronze.threat_intel_raw
# Trigger: daily (scheduled via threat-intel-pipeline Databricks job)
# -----------------------------------------------------------------------------

# COMMAND ----------

# MAGIC %run ./00_threat_intel_common

# COMMAND ----------

import csv
import requests
from datetime import datetime, timezone
from pyspark.sql.functions import current_timestamp

# ─────────────────────────────────────────────────────────────────────────────
# REQUEST CONFIGURATION
# ─────────────────────────────────────────────────────────────────────────────
# 30-second connect+read timeout is generous for plain-text files but protects
# against a slow or unresponsive feed host hanging the entire job run.
REQUEST_TIMEOUT_SECONDS = 30

# ─────────────────────────────────────────────────────────────────────────────
# FETCH TIMESTAMP
# ─────────────────────────────────────────────────────────────────────────────
# A single timestamp for all feeds in this run. The silver MERGE identifies
# "the latest batch per feed" with GROUP BY feed_name / MAX(fetch_timestamp),
# so all rows from a given run must share the same value.
fetch_ts = datetime.now(timezone.utc)
print(f"Run fetch timestamp: {fetch_ts.isoformat()}")

# ═════════════════════════════════════════════════════════════════════════════
# PER-FEED PARSERS
# ═════════════════════════════════════════════════════════════════════════════
# Each parser receives the raw response text and returns a list of dicts.
# Keys required in every dict: ioc_raw_value, indicator_type_hint, extra_fields.
# feed_name and fetch_timestamp are attached after parsing in the fetch loop.

def parse_feodo_tracker(content):
    """
    Parse Feodo Tracker CSV blocklist.

    Expected columns (post-comment-header):
      dst_ip, dst_port, c2_status, first_seen_utc, last_seen_utc, malware

    extra_fields captures port, status, and malware family — these align with
    the silver.threat_intel_network dest_port and malware_family columns.
    The first_seen / last_seen columns from the feed are intentionally NOT
    stored; our own first_seen_at / last_seen_at in silver serve that purpose.
    """
    rows = []
    # Skip comment lines before handing to DictReader — comment lines start
    # with '#' and include the Feodo header block above the CSV header row.
    non_comment_lines = [ln for ln in content.splitlines() if not ln.startswith("#")]
    if not non_comment_lines:
        return rows
    reader = csv.DictReader(non_comment_lines)
    for r in reader:
        ip = (r.get("dst_ip") or r.get("ip_address") or "").strip()
        if not ip:
            continue
        rows.append({
            "ioc_raw_value":       ip,
            "indicator_type_hint": "ipv4",   # Feodo only publishes single IPs
            "extra_fields": {
                "port":    (r.get("dst_port")   or "").strip(),
                "status":  (r.get("c2_status")  or "").strip(),
                "malware": (r.get("malware")    or "").strip(),
            },
        })
    return rows


def parse_emerging_threats(content):
    """
    Parse Emerging Threats compromised IP plain-text list.
    Format: one IP (or CIDR) per line; lines starting with '#' are comments.
    This feed does not provide per-indicator metadata.
    """
    rows = []
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Classify as CIDR or single IP — ET occasionally includes ranges.
        hint = "cidr4" if "/" in line else "ipv4"
        rows.append({
            "ioc_raw_value":       line,
            "indicator_type_hint": hint,
            "extra_fields":        {},
        })
    return rows


def parse_ipsum(content):
    """
    Parse IPsum reputation list.
    Format: IP <TAB> score  (# comment lines skipped)
    'score' = number of upstream threat lists the IP appears on (1–20+).
    Stored in extra_fields["score"] for silver to apply categorical normalization.
    """
    rows = []
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        ip, score = parts[0].strip(), parts[1].strip()
        if not ip:
            continue
        rows.append({
            "ioc_raw_value":       ip,
            "indicator_type_hint": "ipv4",
            "extra_fields":        {"score": score},
        })
    return rows


# Map feed format key to its parser function.
PARSERS = {
    "csv":       parse_feodo_tracker,
    "plaintext": parse_emerging_threats,
    "ipsum":     parse_ipsum,
}

# ═════════════════════════════════════════════════════════════════════════════
# FETCH AND PARSE ALL FEEDS
# ═════════════════════════════════════════════════════════════════════════════

all_rows   = []
feed_stats = {}

for feed_name, config in FEED_CONFIGS.items():
    url    = config["url"]
    fmt    = config["format"]
    parser = PARSERS[fmt]
    print(f"\nFetching {feed_name} ...")
    print(f"  URL: {url}")

    try:
        response = requests.get(url, timeout=REQUEST_TIMEOUT_SECONDS)
        response.raise_for_status()

        parsed = parser(response.text)

        # Attach run-level fields — same for every row within a feed in this run.
        for row in parsed:
            row["feed_name"]       = feed_name
            row["fetch_timestamp"] = fetch_ts

        all_rows.extend(parsed)
        feed_stats[feed_name] = {"status": "ok", "rows": len(parsed)}
        print(f"  {feed_name}: {len(parsed)} indicators parsed successfully.")

    except requests.exceptions.Timeout:
        # Feed timed out — skip this feed, continue with others.
        # Existing silver indicators for this feed will retain their last_seen_at
        # until their 2× TTL expires naturally.
        msg = f"Timeout after {REQUEST_TIMEOUT_SECONDS}s"
        feed_stats[feed_name] = {"status": "skipped", "reason": msg}
        print(f"  WARNING: {feed_name} skipped — {msg}")

    except requests.exceptions.HTTPError as e:
        msg = f"HTTP {e.response.status_code} from {url}"
        feed_stats[feed_name] = {"status": "skipped", "reason": msg}
        print(f"  WARNING: {feed_name} skipped — {msg}")

    except Exception as e:
        # Covers connection errors, parse errors, and unexpected failures.
        msg = str(e)[:300]
        feed_stats[feed_name] = {"status": "skipped", "reason": msg}
        print(f"  WARNING: {feed_name} skipped — {msg}")

print(f"\nFeed summary: {feed_stats}")
print(f"Total indicators to write: {len(all_rows)}")

# Abort if every feed failed — writing an empty batch to bronze would cause
# the silver MERGE to find no new data and potentially not refresh last_seen_at,
# which could lead to premature expiry of valid indicators.
if not all_rows:
    raise RuntimeError(
        "All feeds failed or returned zero indicators. "
        "Inspect the feed_stats above for per-feed failure reasons. "
        "Aborting to prevent a misleading empty bronze batch."
    )

# ═════════════════════════════════════════════════════════════════════════════
# WRITE TO BRONZE TABLE
# ═════════════════════════════════════════════════════════════════════════════
# Build rows as plain dicts matching BRONZE_TI_SCHEMA. Python dict → Spark Row
# conversion handles the MapType for extra_fields automatically.
# saveAsTable creates the table on first run; appends on subsequent runs.
# mergeSchema handles any evolution in extra_fields contents across feeds.

bronze_rows = [
    {
        "ioc_raw_value":       r["ioc_raw_value"],
        "indicator_type_hint": r.get("indicator_type_hint"),
        "feed_name":           r["feed_name"],
        "fetch_timestamp":     r["fetch_timestamp"],
        "extra_fields":        r.get("extra_fields") or {},
        "_ingested_at":        fetch_ts,
    }
    for r in all_rows
]

bronze_df = spark.createDataFrame(bronze_rows, schema=BRONZE_TI_SCHEMA)

(
    bronze_df
    .write
    .format("delta")
    .mode("append")
    .option("mergeSchema", "true")
    .saveAsTable(BRONZE_TI_TABLE)
)

total_after_write = spark.table(BRONZE_TI_TABLE).count()
print(f"\nBronze write complete.")
print(f"  Rows written this run: {len(all_rows)}")
print(f"  Total rows in {BRONZE_TI_TABLE}: {total_after_write}")

# ═════════════════════════════════════════════════════════════════════════════
# BRONZE RETENTION CLEANUP
# ═════════════════════════════════════════════════════════════════════════════
# Hard delete rows older than 14 days to prevent unbounded table growth.
# Operates on _ingested_at (Databricks write time) so that any re-ingested
# or backfilled data is subject to the same cleanup window.
#
# 14-day window rationale:
#   - Longest feed TTL is 30 days (Feodo), so silver will fully process and
#     hard-delete those indicators well within 14 days of bronze ingestion.
#   - 14 days provides comfortable headroom to reprocess bronze if silver fails.
#   - At ~15K rows/day, 14 days = ~210K rows max — well within Delta limits.

rows_before_cleanup = spark.table(BRONZE_TI_TABLE).count()

spark.sql(f"""
    DELETE FROM {BRONZE_TI_TABLE}
    WHERE _ingested_at < current_timestamp() - INTERVAL 14 DAYS
""")

rows_after_cleanup = spark.table(BRONZE_TI_TABLE).count()
deleted = rows_before_cleanup - rows_after_cleanup
print(f"\nBronze retention cleanup: deleted {deleted} rows older than 14 days.")
print(f"  Rows remaining: {rows_after_cleanup}")
